version: '3.8'
services:
  routehelper:
    build: .
    container_name: routehelper-app
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
# Add more services (e.g., db, reverse proxy) as needed
